package com.activitytransitions_demo;

/**
 * Created by sonu on 06/08/16.
 */

public class User {
    static final User[] USER = new User[]{
            new User("Surender", "#F44336", "+91 9846342617", "surender@example.com", "Bangalore"),
            new User("Vikas", "#9C27B0", "+91 9876093891", "vikas@example.com", "Chennai"),
            new User("Yug", "#2196F3", "+91 8765438901", "yug@example.com", "Jaipur"),
            new User("Puneet", "#009688", "+91 9876543212", "puneet@example.com", "Lucknow"),
            new User("Navneet", "#FFC107", "+91 8974327812", "navneet@example.com", "Ahmedabad"),
            new User("Kajol", "#8BC34A", "+91 9845123471", "kajol@example.com", "Mumbai"),
            new User("Radha", "#FF5722", "+91 7896514521", "radha@gian.lu", "Chandigarh"),
            new User("Suresh", "#607D8B", "+91 98640826137", "suresh@example.com", "Rajasthan"),
    };

    // The fields associated to the User
    private final String mName, mPhone, mEmail, mCity, mColor;

    private User(String name, String color, String phone, String email, String city) {
        mName = name;
        mColor = color;
        mPhone = phone;
        mEmail = email;
        mCity = city;
    }

    // This method allows to get the item associated to a particular id,
    // uniquely generated by the method getId defined below
    static User getItem(int id) {
        for (User item : USER) {
            if (item.getId() == id) {
                return item;
            }
        }
        return null;
    }

    // since mName and mPhone combined are surely unique,
    // we don't need to add another id field
    public int getId() {
        return mName.hashCode() + mPhone.hashCode();
    }

    static enum Field {
        NAME, COLOR, PHONE, EMAIL, CITY
    }

    String get(Field f) {
        switch (f) {
            case COLOR:
                return mColor;
            case PHONE:
                return mPhone;
            case EMAIL:
                return mEmail;
            case CITY:
                return mCity;
            case NAME:
            default:
                return mName;
        }
    }
}
